#!/usr/bin/env python3
"""Rebuild sitemap.xml from the real pages, with real <lastmod> dates.

Written 2026-09-16. The hand-maintained sitemap had every <lastmod> frozen at
2026-08-31 while pages were actually edited on the 14th and 16th, so crawlers
had no reason to come back and the live search result was still showing copy
from before the rewrite. It also missed bring-a-shop.html and support.html
entirely. Dates now come from git (the last commit that touched the file),
falling back to the file's own mtime for anything not committed yet, so they
cannot drift again.

Priority/changefreq are advisory only - search engines largely ignore both -
so the tiers here are kept simple rather than tuned.

Run from the repo root:  python3 scripts/build_sitemap.py
"""
import subprocess, pathlib, datetime, re, sys

SITE = "https://clocal.co.uk"
ROOT = pathlib.Path(__file__).resolve().parent.parent

# Top-level .html files only. Everything under r/ and academy/ is deliberately
# noindex,nofollow (group redirects and the internal academy), so listing them
# would be telling Google to crawl pages we have told it to ignore.
def pages():
    for p in sorted(ROOT.glob("*.html")):
        html = p.read_text(encoding="utf-8")
        if re.search(r'name="robots"[^>]*noindex', html):
            continue
        yield p

def lastmod(p: pathlib.Path) -> str:
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%cs", "--", p.name],
            cwd=ROOT, capture_output=True, text=True, check=True,
        ).stdout.strip()
        if out:
            return out
    except Exception:
        pass
    return datetime.date.fromtimestamp(p.stat().st_mtime).isoformat()

# Tier by role, not by guesswork: the homepage, then the hub and the two
# "things to do" guides that the area pages all link up into, then the area
# pages, then the pages that exist for people who already found us.
HUB = {"hidden-gems-belfast.html", "things-to-do-south-belfast.html",
       "things-to-do-east-belfast.html"}
SUPPORTING = {"creators.html", "partners.html", "bring-a-shop.html",
              "support.html", "privacy.html", "terms.html"}

def tier(name):
    if name == "index.html":
        return "1.0", "weekly"
    if name in HUB:
        return "0.9", "weekly"
    if name in SUPPORTING:
        return "0.4", "monthly"
    return "0.8", "weekly"

def loc(name):
    return f"{SITE}/" if name == "index.html" else f"{SITE}/{name}"

lines = ['<?xml version="1.0" encoding="UTF-8"?>',
         '<!-- Generated by scripts/build_sitemap.py - do not hand-edit, rerun it. -->',
         '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
count = 0
for p in pages():
    prio, freq = tier(p.name)
    lines += ["  <url>",
              f"    <loc>{loc(p.name)}</loc>",
              f"    <lastmod>{lastmod(p)}</lastmod>",
              f"    <changefreq>{freq}</changefreq>",
              f"    <priority>{prio}</priority>",
              "  </url>"]
    count += 1
lines.append("</urlset>")

(ROOT / "sitemap.xml").write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"sitemap.xml written: {count} urls", file=sys.stderr)
